### ISSUE TITLE
User setup form failing

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#315] opened 2024-01-19 19:29 UTC
**Describe the bug**
User is met with requirements of the form to be valid even though they are, making the user not able to progress with the setup System.

**To Reproduce**
1. Sign up on the website
2. User is met with the Setup interface, and fills it up with the appropriate fields.
3. User is met with 'Avatar, Display Name and Bio Required' even though they are in the fields.

**Screenshots**
![image](https://github.com/awaazo/awaazo/assets/31280516/83ddd738-3da3-4f5c-97d6-26e35b321259)

**Comment by mathieutrudeau** [comment] 2024-01-20 21:03
The issue seems to be caused by the EmailService. 
![Capture](https://github.com/awaazo/awaazo/assets/46968018/aa186f84-77bf-4e4a-a51d-5e8bf18d7aa9)

**Comment by mathieutrudeau** [comment] 2024-01-20 21:10
> The issue seems to be caused by the EmailService. ![Capture](https://private-user-images.githubusercontent.com/46968018/298307520-aa186f84-77bf-4e4a-a51d-5e8bf18d7aa9.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODQ5MTcsIm5iZiI6MTcwNTc4NDYxNywicGF0aCI6Ii80Njk2ODAxOC8yOTgzMDc1MjAtYWExODZmODQtNzdiZi00ZTRhLWE1MWQtNWU4YmYxOGQ3YWE5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIxMDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZDQ4NWNiNzkwMmU0MTc1ZjdlNzZhODJiMWUwYzY2ODkwMTg5NmEzMjI2MWJlNmY0ZTRkOWI2YmY5ZWU4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGpKAqsne34V3g49WansGrpKLZoEspQ2fDprTrNBR3k)

Turns out this is due to having an incomplete appsettings.json file.

**Comment by mathieutrudeau** [comment] 2024-01-20 21:14
The bug seems to be due to a migration error and will be fixed in the next PR.

**Closed** 2024-01-22 17:11 UTC
Labels: 🛠️ goal: fix, 🔢 points: 1, 🟨 priority: medium
